---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prom-stack
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: kube-prom-stack
      interval: 12h
  values:
    grafana:
      adminPassword: 7!e1w$Gw3rWWAg&7JrQ4h69aco%#IAgZ
      service:
        portName: http-web
